export const wordObject = {
    Animais: ['ALBATROZ',  'ALPACA',  'ANCHOVA',  'BACALHAU',  'BADEJO',  'BARRACUDA',  'BELUGA',  'CHINCHILA',  'CRACA',  'ESCARAVELHO',  'GERBO',  'GNU',  'GRALHA',  'HAMSTER',  'LHAMA',  'LINCE',  'MARRECO',  'MELRO',  'OCAPI',  'PELICANO',  'PERCEVEJO',  'PIRILAMPO',  'QUATI',  'ROUXINOL',  'SANGUESSUGA',  'SURUCUCU',  'TAPIR',  'TEXUGO'],
    Objetos: ["AMPULHETA",  "ANZOL",  "ALMOFARIZ",  "BOTIJA",  "CANDELABRO",  "DEDALEIRA",  "DESFIBRILADOR",  "ECHARPE",  "ESTRIBO",  "FAGOTE",  "FANTOCHE",  "FREEZER",  "NAVALHA",  "JALECO",  "MODEM",  "NEBULIZADOR",  "NOVELO",  "QUEPE",  "SELIM",  "SINTETIZADOR",  "SPRAY",  "URINOL",  "VUVUZELA",  "WEBCAM",  "XADREZ",  "XILOFONE"],
    Frutas: ["ALFARROBA", "BERGAMOTA", "CIRIGUELA", "CRANBERRY", "FEIJOA", "GROSELHA", "IMBU", "JENIPAPO", "KIWI", "LICHIA", "MEXERICA", "NECTARINA", "PEQUI", "PISTACHE", "POMELO", "SAGUARAJI"],
    Vulcões: ["LAVA", "QUENTE", "CINZA", "ROCHA", "CALOR", "DERRETIMENTO"], 
    Cozinha: ["PANELAS", "COLHER", "RALADOR", "FRITADEIRA", "ELETRODOMESTICOS", "DEPURADOR", "CHAIRA", "TALHER",],
    Profissões: ["APICULTOR",    "AUDITOR",    "BARTENDER",    "CERIMONIALISTA", "CHEF",    "COACH",    "DESEMBARGADOR",    "DESPACHANTE",    "ENDOCRINOLOGISTA",    "EMBAIXADOR",    "HEADHUNTER",    "JUIZ",    "PIZZAIOLO",    "PERITO",    "QUIROPRATA",    "ROTEIRIZADOR",    "SILVICULTOR",    "TRADER"],
    Jardim: ["FLORES", "MINHOCA", "VASO", "TERRA", "PEDRA", "GRAMA", "FONTE"],
    País: ["BRASIL", "ALEMANHA", "CHINA", "PORTUGAL", "CUBA", "NEPAL", "SURINAME", "UGANDA", "NORUEGA", "IRAQUE", "BOTSWANA"],
    Escola: ["LIVRO", "CANETA", "BORRACHA", "CADEIRA", "CADERNO", "QUADRO", "GIZ", "PROVA", "APAGADOR", "MATERIAL", "DISCIPLINA", "ENSINO", "ALUNO", "PROFESSOR", "CURSO", "AULA", "NOTA", "APRENDIZADO"],
    Prédio: ['ELEVADOR', 'PORTARIA', 'GARAGEM', 'ESCADARIA', 'JANELA', 'VARANDA', 'ANDAR', 'TELHADO', 'CIMENTO', 'BLOCOS', 'CATAVENTO', 'ESTRUTURA', 'REVESTIMENTO', 'APARTAMENTO', 'CIMENTEIRA'],
    Árvore: ["FOLHA", "RAMO", "TRONCO", "RAIZ", "FRUTO", "SEMENTE", "GALHO", "FLORESTA", "FLORESCER", "JARDIM", "AROEIRA", "JABUTICABEIRA", "CEREJEIRA", "MANGUEIRA", "LARANJEIRA", "CAJUEIRO", "PINHEIRO"],
    Filme: ['CINEMA', 'DIRETOR', 'ROTEIRISTA', 'FIGURINO', 'TRILHA', 'EFEITOS', 'FESTIVAL', 'TAPETE', 'HOLLYWOOD', 'CINEASTA', 'BILHETERIA', 'OSCAR'], 
}